apiVersion: v1
kind: Service
metadata:
  name: uporabniki-service
  labels: 
    app: uporabniki
spec:
  type: LoadBalancer
  selector:
    app: uporabniki
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
