services:
  uporabniki_storitev:
    build:
      context: ./services/1uporabniki-storitev
      dockerfile: ./config/Dockerfile
    container_name: uporabniki_storitev
    image: al96152/uporabniki:latest
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:123121@db_uporabniki:5432/uporabniki
    depends_on:
      - db_uporabniki

  skupine_storitev:
    build:
      context: ./services/2skupine-storitev
      dockerfile: ./config/Dockerfile
    container_name: skupine_storitev
    image: al96152/skupine:latest
    ports:
      - "5001:5001"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:123121@db_skupine:5432/skupine
    depends_on:
      - db_skupine

  stroski_storitev:
    build:
      context: ./services/3stroski-storitev
      dockerfile: ./config/Dockerfile
    container_name: stroski_storitev
    image: al96152/stroski:latest
    ports:
      - "5002:5002"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:123121@db_stroski:5432/stroski
    depends_on:
      - db_stroski

  analiza_storitev:
    build:
      context: ./services/4analiza-storitev
      dockerfile: ./config/Dockerfile
    container_name: analiza_storitev
    image: al96152/analiza:latest
    ports:
      - "5003:5003"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:123121@db_analiza:5432/analiza
    depends_on:
      - db_analiza

  db_uporabniki:
    image: postgres:17
    container_name: db_uporabniki
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123121
      POSTGRES_DB: uporabniki
    ports:
      - "5433:5432"

  db_skupine:
    image: postgres:17
    container_name: db_skupine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123121
      POSTGRES_DB: skupine
    ports:
      - "5434:5432"

  db_stroski:
    image: postgres:17
    container_name: db_stroski
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123121
      POSTGRES_DB: stroski
    ports:
      - "5435:5432"

  db_analiza:
    image: postgres:17
    container_name: db_analiza
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123121
      POSTGRES_DB: analiza
    ports:
      - "5436:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092