apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appDeploymentName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.containerName }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.targetPort }}
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 5000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: 5000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   timeoutSeconds: 1
        #   failureThreshold: 3
