apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appServiceName }}
  labels: 
    app: {{ .Values.appName }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.targetPort }}
