apiVersion: v1
kind: Service
metadata:
  name: skupine-service
  labels:
    app: skupine
spec:
  type: LoadBalancer
  selector:
    app: skupine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
