apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupine-deployment
  labels: 
    app: skupine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skupine
  template:
    metadata:
      labels:
        app: skupine
    spec:
      containers:
      - name: skupine
        image: al96152/skupine:v1.0
        ports:
        - containerPort: 5001
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 5001
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: 5001
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   timeoutSeconds: 1
        #   failureThreshold: 3
