apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupine-deployment
  labels: 
    app: skupine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skupine
  template:
    metadata:
      labels:
        app: skupine
    spec:
      containers:
      - name: skupine
        image: al96152/skupine:v1.0
        ports:
        - containerPort: 5001
