apiVersion: v1
kind: Service
metadata:
  name: analiza-service
  labels:
    app: analiza
spec:
  type: LoadBalancer
  selector:
    app: analiza
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003
