apiVersion: apps/v1
kind: Deployment
metadata:
  name: stroski-deployment
  labels:
    app: stroski
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stroski
  template:
    metadata:
      labels:
        app: stroski
    spec:
      containers:
      - name: stroski
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5002
        livenessProbe:
          httpGet:
            path: {{ .Values.livelinessProbe.httpGet.path }}
            port: {{ .Values.livelinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.livelinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livelinessProbe.periodSeconds }}
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: 1
          failureThreshold: 3
