apiVersion: apps/v1
kind: Deployment
metadata:
  name: stroski-deployment
  labels:
    app: stroski
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stroski
  template:
    metadata:
      labels:
        app: stroski
    spec:
      containers:
      - name: stroski
        image: al96152/stroski:v1.0
        ports:
        - containerPort: 5002
