apiVersion: apps/v1
kind: Deployment
metadata:
  name: analiza-deployment
  labels:
    app: analiza
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analiza
  template:
    metadata:
      labels:
        app: analiza
    spec:
      containers:
      - name: analiza
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5003
        livenessProbe:
          httpGet:
            path: {{ .Values.livelinessProbe.httpGet.path }}
            port: {{ .Values.livelinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.livelinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livelinessProbe.periodSeconds }}
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: 1
          failureThreshold: 3
