apiVersion: v1
kind: Service
metadata:
  name: stroski-service
  labels:
    app: stroski
spec:
  type: LoadBalancer
  selector:
    app: stroski
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
