name: Docker Image CI

on:
  push:
    branches: [ "test" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push uporabniki
      run: |
        docker build -t al96152/uporabniki:latest
        docker push al96152/uporabniki:latest
    -
      name: Build and push skupine
      run: |
        docker build -t al96152/skupine:latest
        docker push al96152/skupine:latest
    -
      name: Build and push stroski
      run: |
        docker build -t al96152/stroski:latest
        docker push al96152/stroski:latest
    -
      name: Build and push analiza
      run: |
        docker build -t al96152/analiza:latest
        docker push al96152/analiza:latest
