name: Docker Image CI

on:
  push:
    branches: [ "test" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push images with Docker Compose
        run: |
          cd ..
          docker compose build
          docker compose push
